name: test

on: [push, pull_request]

jobs:

  quality-gate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.0.1
      with:
        go-version: ^1.22

    - name: Test
      run: ./scripts/test.sh
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
        
