name: test

on: [push]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: ^1.22

      - name: Test
        run: ./scripts/test.sh
